var titles = [
  "JULIA OUVINDO CRYSTAL CASTLE",
  "BOMBO TRAVADO",
  "BATEU O BOLONHA",
  "HOMEM ARANHA RUPESTRE",
  "NELSON DE ROUPAO",
  "PATY INDIGNADA",
  "BOLO DA DIANA",
  "FILA DE SEXO NO CARRO DO RAUL",
  "VOMITO NOS VIDEOGAMES",
  "BRENONINHO",
  "MALU DOIDONA",
  "JOAO MACEWICIUS DORMINDO",
  "IAGO IGOR GOD",
  "CYNOLA",
  "YOSHI DE CUECA VERMELHA",
  "TORRESGUI TOMOU UMA CUZADA",
  "LUCAS OLIVEIRA TRAVADO",
  "LUCAS FARIA PUTASSO",
  "ESQUECI FAZ OUTRA",
  "3 PARES DE SAPATO",
  "RESPEITINHA",
  "QUEM E MEU MENINAO",
  "NATALIA FICOU SOLTEIRA",
  "JOSE CANSADO",
  "CAINAN PRESO COM FITAS",
  "TBTIAGO",
  "SABONETE DO KENJI E DA GABI",
  "THIS IS CASSOSHI",
  "PALOMA E FERNANDO PERDIDOS",
  "PETERPETERPETER",
  "LEOZAO S2",
  "MATHEUS OTAVIO NEM DORMIU",
  "FOTOGRAFIAS BY BUNHO",
  "EU TROUXE O FEIJAO - NANA",
  "RICARDOBOMBOM",
  "TOBOGA FRUSTRADO",
  "IAGO IGOR PRODUCOES",
  "DJ JULIAO DUAS HORAS DE FUNK SEM INTERVALO",
  "URSAO DA CASSOSHI",
  "MARCIO ROGERIO",
  "CREATURE COMFORT",
  "NO TEARS LEFT TO CRY",
  "RUAAAAAN",
  "BOMBOOOOOOO",
  "BARRIGA SOLTA"
];

var text ="BACK TO THE CASSOSHI";
function doo(){
    for (var i = 0; i < titles.length; i++) {
      text = text +" • "+ titles[i];
    }
    document.getElementById("Q").innerHTML = text;

}

function doCredits(){
  var text ="BACK TO THE CASSOSHI";
  for (var i = 0; i < titles.length; i++) {
    text = text +"     "+ titles[i];
  }
  document.getElementById("IDmarquee").innerHTML = text;
  $('.marquee').marquee();
}
